//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Visita
    {
        public int ID { get; set; }

        [Display(Name = "Motivo de la visita")]
        public string Motivovisita { get; set; }
        [Display(Name = "Fecha de la visita")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Fechavisita { get; set; }
        [Display(Name = "Hora de entrada")]
        [DataType(DataType.Time)]
        public Nullable<System.TimeSpan> Horaentrada { get; set; }
        [Display(Name = "Hora de salida")]
        [DataType(DataType.Time)]
        public Nullable<System.TimeSpan> Horasalida { get; set; }
        [Display(Name = "Nombre del contacto")]
        public Nullable<int> IdNombre { get; set; }
        [Display(Name = "Persona que lo recibio")]
        public string PersonaRecibidora { get; set; }
        public virtual Contactos Contactos { get; set; }
    }
}
